% This program reads in Shifted_c40 files and plots mechanical data. It
% provides ability to pick up points and yield y values w.r.t time.

%% Import
[filename, filepath] = uigetfile...
    ('*.c40', 'Please select c40 files generated by quickview');
if filename == 0
    return
end

fileID = fopen([filepath,filename]);
delimiter = '\t';
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f';
ROGAc40cell = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines', 1, 'ReturnOnError', false);
fclose(fileID);

ROGAc40matwithNaN = cell2mat(ROGAc40cell);
M = ROGAc40matwithNaN(3:end-2,:);

%% Plot or Re-plot

% Parameters
indexOfTime = 21;
indicesToPlot = [24, 27, 32];
indicesToSmoothen = [24];
smoothSpan = 10;
indicesToDot = [24, 27, 32];

% Plot
T = M(:,indexOfTime);
if isvalid(fig)
    figure(fig);
    xRange = xlim;
    leftInd = find(T > xRange(1),1,'first');
    rightInd = find(T < xRange(2),1,'last');
    clf(fig);
else
    fig = figure('name', ['pick stick slip from ',filename]);
    leftInd = 1;
    rightInd = length(M);
    xRange = [T(leftInd), T(rightInd)];
end

hold on
for i = 1:length(indicesToPlot)
    smoothening = 1;
    if ismember(indicesToPlot(i), indicesToSmoothen)
        smoothening = smoothSpan;
    end
    toPlot = smooth(M(:,indicesToPlot(i)), smoothening);
    toPlot = toPlot - min(toPlot(leftInd:rightInd));
    toPlot = toPlot/max(toPlot(leftInd:rightInd));
    if ismember(indicesToPlot(i), indicesToDot)
        plot(T,toPlot,'linewidth',2,'marker','*');
    else
        plot(T,toPlot,'linewidth',2);
    end
end
hold off
xlim(xRange);
legend(cellstr(num2str(indicesToPlot')));

%% Reset Zoom
xlim auto
ylim auto

%% Export Point
format longE
try
    dcm_obj = datacursormode(gcf);
    c_info = getCursorInfo(dcm_obj);
    c_info = fliplr(c_info);
    xValue = c_info(1).Position(1);
    ind = find(T > xValue,1,'first');
    disp(['Time is ',num2str(xValue)]);
    disp(['Columns are ', num2str(indicesToPlot)]);
    disp('Values are:');
    disp(M(ind, indicesToPlot)');
catch ME
    error('Please repick.');
end