% This program reads in Shifted_c40 files and plots mechanical data. It
% provides ability to pick up points and yield y values w.r.t time.

%% Import
[filename, filepath] = uigetfile...
    ('*.c40', 'Please select c40 files generated by quickview');
if filename == 0
    return
end

fileID = fopen([filepath,filename]);
delimiter = '\t';
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f';
ROGAc40cell = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines', 1, 'ReturnOnError', false);
fclose(fileID);

ROGAc40matwithNaN = cell2mat(ROGAc40cell);
M = ROGAc40matwithNaN(3:end-2,:);

%% Re-initialize Database
DB = [];

%% Plot or Re-plot

% Parameters
indexOfTime = 21;
indicesToPlot = [24, 25, 32];
indicesToSmoothen = [24];
smoothSpan = 10;
indicesToDot = [25];
linewidth = 1;
ylimits = [-0.1, 1.1];
marker = '*';

% Plot
T = M(:,indexOfTime);
if exist('fig','var') && isvalid(fig)
    figure(fig);
    xRange = xlim;
    leftInd = find(T > xRange(1),1,'first');
    rightInd = find(T < xRange(2),1,'last');
    clf(fig);
else
    fig = figure('name', ['pick stick slip from ',filename]);
    leftInd = 1;
    rightInd = length(M);
    xRange = [T(leftInd), T(rightInd)];
end

hold on
for i = 1:length(indicesToPlot)
    smoothening = 1;
    if ismember(indicesToPlot(i), indicesToSmoothen)
        smoothening = smoothSpan;
    end
    toPlot = smooth(M(:,indicesToPlot(i)), smoothening);
    toPlot = toPlot - min(toPlot(leftInd:rightInd));
    toPlot = toPlot/max(toPlot(leftInd:rightInd));
    if ismember(indicesToPlot(i), indicesToDot)
        plot(T,toPlot,'linewidth',linewidth,'marker',marker);
    else
        plot(T,toPlot,'linewidth',linewidth);
    end
end
hold off
xlim(xRange);
ylim(ylimits);
legend(cellstr(num2str(indicesToPlot')));

if 1
    return
end

%% Reset Zoom
xlim auto
ylim auto

%% Export Point
format longE
try
    dcm_obj = datacursormode(gcf);
    c_info = getCursorInfo(dcm_obj);
    if (mod(length(c_info),2) == 1)
        warning('You picked odd number of points.');
        return
    end
    c_info = fliplr(c_info);
    tempData = [];
    for i = 1:length(c_info)
        % display
        xValue = c_info(i).Position(1);
        xInd = find(T > xValue,1,'first');  
        colInd = c_info(i).Target.DisplayName;
        disp(['Time ',num2str(xValue),' Column ', colInd]);
        disp([xValue M(xInd, str2double(colInd))]);
        % store
        tempData = [tempData; [str2double(colInd) xValue M(xInd, str2double(colInd))]];
    end
    tempData = sortrows(tempData,[1 2]);
    tempData2 = reshape(tempData(:,2:3)',[],1);
    tempData3 = tempData2';
    DB = [DB;tempData3];
catch ME
    error('Please repick.');
end

%% Undo the previous picking
DB = DB(1:end-1,:);

%% Export to Excel File
[~,name,~] = fileparts(filename);
header_ = cellstr(num2str(indicesToPlot'));
headers = {};
suffix = ['t1';'v1';'t2';'v2'];
for i = 1:4
    header = header_;
    for j = 1:length(header)
        header{j} = [header{j},'_',suffix(i,:)];
    end
    headers = [headers header];
end
headers = reshape(headers',[],1)';
xlswrite([filepath,'Stick_slip_',name,'.xlsx'],...
    headers, 'Sheet1', 'A1');
xlswrite([filepath,'Stick_slip_',name,'.xlsx'],...
    DB, 'Sheet1', 'A2');